version: '3.8'

services:
  # bancos
  postgres-products:
    image: postgres:15
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: prod_s3cret_!A9
      POSTGRES_DB: products_db
    volumes:
      - products_pgdata:/var/lib/postgresql/data
    networks: [ app-net ]

  postgres-users:
    image: postgres:15
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: usr_s3cret_!C8
      POSTGRES_DB: users_db
    volumes:
      - users_pgdata:/var/lib/postgresql/data
    networks: [ app-net ]

  postgres-payments:
    image: postgres:15
    environment:
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: paym_s3cret_!B7
      POSTGRES_DB: payments_db
    volumes:
      - payments_pgdata:/var/lib/postgresql/data
    networks: [ app-net ]

  mongo-orders:
    image: mongo:7
    volumes:
      - mongo_orders_data:/data/db
    networks: [ app-net ]

  # serviÃ§os via kong
  products:
    build: ./products
    container_name: ms_products
    depends_on:
      - postgres-products
    environment:
      DATABASE_URL: postgresql://products_user:prod_s3cret_!A9@postgres-products:5432/products_db
      PORT: 3000
    networks: [ app-net ]
    command: >
      sh -c "
        sleep 10 &&
        npx prisma db push &&
        node prisma/seed.js &&
        npm run start
      "

  users:
    build: ./users
    container_name: ms_users
    depends_on:
      - postgres-users
    environment:
      DATABASE_URL: postgresql://users_user:usr_s3cret_!C8@postgres-users:5432/users_db
      PORT: 3000
      JWT_SECRET: super_secret_key_forza_users_!A1
    networks: [ app-net ]
    command: >
      sh -c "
        sleep 10 &&
        npx prisma db push &&
        node prisma/seed.js &&
        npm run start
      "

  orders:
    build: ./orders
    container_name: ms_orders
    depends_on:
      - mongo-orders
      - products
      - kafka
    environment:
      MONGO_URI: mongodb://mongo-orders:27017/orders_db
      PORT: 3000
      PRODUCTS_SERVICE_URL: http://products:3000
      KAFKA_BROKER: kafka:9092
    networks: [ app-net ]
    command: >
      sh -c "
        sleep 10 &&
        node seed.js &&
        npm run start
      "

  payments:
    build: ./payments
    container_name: ms_payments
    depends_on:
      - postgres-payments
      - kafka
      - orders
      - redis-cache
    environment:
      DATABASE_URL: postgresql://payments_user:paym_s3cret_!B7@postgres-payments:5432/payments_db
      PORT: 3000
      KAFKA_BROKER: kafka:9092
      ORDERS_SERVICE_URL: http://orders:3000
      PRODUCTS_SERVICE_URL: http://products:3000
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    networks: [ app-net ]
    command: >
      sh -c "
        sleep 10 &&
        npx prisma db push &&
        node prisma/seed.js &&
        npm run start
      "

  notification:
    build: ./notification
    container_name: ms_notification
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      DATABASE_URL: file:./dev.db
      PORT: 3000
      RABBITMQ_URL: amqp://rabbitmq
      SMTP_HOST: smtp.ethereal.email
      SMTP_PORT: 587
      SMTP_USER: forza.notify@example.com
      SMTP_PASS: senha_teste
    networks: [ app-net ]
    command: >
      sh -c "sleep 8 && npx prisma db push && npm run start"


  # extras
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [ app-net ]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks: [ app-net ]

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks: [ app-net ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks: [ app-net ]

  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [ app-net ]

  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis-cache
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    networks: [ app-net ]

  kong:
    image: kong:3.4
    container_name: kong_gateway
    restart: always
    depends_on:
      - redis-cache
      - users
      - products
      - orders
      - payments
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    networks: [ app-net ]

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    depends_on:
      - kong
    environment:
      - DB_ADAPTER=sqlite
      - KONGA_HOOK_TIMEOUT=60000
      - TOKEN_SECRET=some_secret_for_konga
      - NODE_ENV=production
      - KONGA_BACKEND_URL=http://kong:8001
    ports:
      - "1337:1337"
    volumes:
      - konga_data:/app/konga.db
    networks: [ app-net ]

volumes:
  products_pgdata: {}
  users_pgdata: {}
  payments_pgdata: {}
  mongo_orders_data: {}
  redis_data: {}
  konga_data: {}

networks:
  app-net:
    driver: bridge
